chatgpt.js
=> Added function to get oringinal elements

chatgpt.js
By the way,
I try to use it at https://github.com/mefengl/chatgpt-sensible,
It really works
=> Fixed wrong button name from `getSubmitButton` to `getSendButton`

chatgpt.js
We should consider adding an eslint config. 
Additionally, the emit function is not functioning properly. Updating the status every second may not be sufficient for real-time updates. Perhaps we can implement a solution that listens to changes in the DOM instead.
=> Added eventEmitter

chatgpt.js
changes:
1. replace all `var` to `let` to avoid typo become runtime errors.
2. changed some function to arrow function to avoid `.bind(this)`
> 
> you have been using the methods appeared after `let` and "arrow function", such as `prepend`.
> So those who can run your script without translation can also use `let` and "arrow function"
> 
> using `let` can avoid the typo mistake runtime errors.
> using `arrow function` can avoid `.bind(this)`
> 
> P.S. you have already used some arrow functions like `if (subAliases.some(subAlias => subAlias.includes(prop))) {` and `let nestedFunction = subAliases.find(element => element.includes('.')).split('.')[1];`
> 
3. organized some function inside for-loop, while-loop, and setTimeout into better manner to avoid memory leakage. (nested functions)
4. …
=> memory issues + syntax fixed

chatgpt.js
`getLastResponse()`, `getLastResponseDiv()`, `getResponse()`, `regenerate()` and `stop()` methods are now inside of `chatgpt.response`.
=> Shortened responses-related methods

chatgpt.js
I think it can be done better but it works :)
=> Added exportChat() method

chatgpt.js
Hi all, I added this method for my own use and thought about open a PR for it, let me know if it is useful.
cheers!
=> Add  method "getContinueGeneratingButton"

chatgpt.js
in `getAccountDetails` and `getChatDetails`
yeah, it works perfectly fine, but I assume you know better ways to achieve the same job, so check the code out.
in addition, by supplying multiple `detail` parameters the user is forced to also supply the `chat` parameter in `getChatDetails`
=> Expanded flexibility of param passing to `getChatDetails()`

chatgpt.js, docs/userguide.md
Some docs are still missing (reference #60 [here](https://github.com/kudoai/chatgpt.js/pull/60#issue-1794999696))
=> Updated documentation as of commit d470bab

chatgpt.js
=> Added access token storing

docs/it/README.md
=> Translated heading

chatgpt.js, docs/USERGUIDE.md, docs/it/README.md
- Updated docs (765ea1f)
- Fixed small unseen error in italian docs
- Fixed parameters validation for shareChat
- Missing `else` keyword
- Missing default value for `method`
=> Updated docs as of commit 765ea1f

chatgpt.js, docs/USERGUIDE.md
because apparently OpenAI removed the shortcut button to clear all chats
=> Fixed clearChats

chatgpt.js, docs/USERGUIDE.md
- Removed redundant 'Chat list is empty' message in `clearChats`
- Added `else` keyword in `getChatData` to avoid multiple calls after errors
- Docs updated to commit 5bd947c
=> Small fixes + Docs updated to commit 5bd947c

docs/README.md, docs/USERGUIDE.md
=> Fix minor typos

chatgpt.js
=> Added console styling to `printAllFunctions`

docs/it/README.md
=> Small translation changes

chatgpt.js
to navigate to the logout endpoint
=> Updated `chatgpt.logout`

chatgpt.js
=> Modified `sidebar.apped` to be more user-friendly

chatgpt.js, docs/USERGUIDE.md
\+ default value added to dropdown so it's not empty
=> Changed `select` to `dropdown`

chatgpt.js
and copied `scheme` object into it with spread syntax
idk if this is the approach you wanted, but it works perfectly fine
=> Added `settings` object & fixed theme-related methods

data/_locales/en_GB/messages.json
Created `en_GB` folder and added a `messages.json` file to it.
=> Created missing folder for en_GB

chatgpt.js
Updated CSS selector for the getRegenerateButton method after ChatGPT web interface update.
=> Updated CSS selector for the getRegenerateButton method

chatgpt.js
SendButton CSS selector fixed.
Stripping only one _ChatGPT_ in the response (it was _ChatGPTChatGPT_).
=> Fixing changes in ChatGPT web interface

docs/ja/README.md
=> docs: update ja/README.md

docs/Id/Readme.md
This enhancement aims to provide a better experience for Russian-speaking users, ensuring they can fully engage with our content and features
=> Create Indonesian README

README.md
The back to top in the last of readme was not working.
=> Back to Top not working in readme

README.md
=> Fixes Nepali link in README

README.md
=> chore(README.md): use callout notation
